# Generated by Django 4.1.7 on 2023-03-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(blank=True, max_length=100, null=True)),
                ('depart_decs', models.TextField()),
            ],
        ),
    ]
